name: Compile with BookML
author: Vincenzo Mantova
description: Compile LaTeX files to HTML via BookML
branding:
  icon: book
  color: blue

inputs:
  checkout:
    description: Checkout the current repository
    default: true
  release:
    description: Create a GitHub release with all the outputs
    default: true
  upload-aux-directory:
    description: Upload the aux directory, including all outputs, longs, and other intermediate files into a GitHub artifact
    default: true
  scheme:
    description: TeX Live scheme to use among 'basic', 'small', 'medium', 'full'
    default: full
  version:
    description: BookML version (if the `bookml` folder is already present, this only affects which Docker image is used)
    default: latest
  replace-bookml:
    description: Replace the `bookml` folder, if present, with the version included in the Docker image
    default: false
  timeout-minutes:
    description: The maximum number of minutes to run BookML before cancelling the build
    default: 6

outputs:
  outputs:
    description: File names of all outputs compiled by BookML
    value: steps.bookml.outputs.outputs
  targets:
    description: File names of all targets that BookML tried to compile
    value: steps.bookml.outputs.targets
  outcome:
    description: Compiling outcome (one of 'success', 'failure', 'timeout', 'invalid', 'cancelled')
    value: steps.bookml.outputs.outcome
  aux-directory-url:
    description: URL of GitHub artifact containing the aux directory
    value: steps.upload-aux-directory.outputs.artifact-url
  release-url:
    description: URL of GitHub release
    value: steps.release.outputs.release-url

runs:
  using: composite
  steps:
    - name: Checkout the current repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    # GitHub does not allow dynamic inputs in 'uses', so we need to pull the Docker image by hand
    - name: Compile with BookML
      id: bookml
      shell: sh
      env:
        SCHEME: ${{ inputs.scheme }}
        VERSION: ${{ inputs.version }}
        REPLACE_BOOKML: ${{ inputs.replace-bookml }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
      run: |
        ### Compile with BookML ###
        "$GITHUB_ACTION_PATH"/compile.sh

    - name: Upload aux directory (all products, including logs)
      uses: actions/upload-artifact@v4
      id: upload-aux-directory
      if: ${{ always() && steps.bookml.outputs.outcome != 'invalid' && inputs.upload-aux-directory == 'true' }}
      with:
        name: aux-directory
        path: ${{ runner.temp }}/auxdir/*
        if-no-files-found: ignore
        include-hidden-files: true

    - name: Create summary and release
      if: ${{ always() }}
      id: release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        JOB_CHECK_RUN_ID: ${{ job.check_run_id }}
        RELEASE: ${{ inputs.release }}
        AUX_URL: ${{ steps.upload-aux-directory.outputs.artifact-url }}
        OUTCOME: ${{ steps.bookml.outcome == 'cancelled' && 'cancelled' || steps.bookml.outputs.outcome }}
        TARGETS: ${{ steps.bookml.outputs.targets }}
        OUTPUTS: ${{ steps.bookml.outputs.outputs }}
        MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        ### Create summary and release ###
        "$GITHUB_ACTION_PATH"/release.sh
