name: Compile with BookML
description: Compile LaTeX files to HTML via BookML
branding:
  icon: book
  color: blue

inputs:
  checkout:
    description: Checkout the current repository
    default: true
  release:
    description: Upload the outputs to a new GitHub release
    default: true
  scheme:
    description: TeX Live scheme to use among 'basic', 'small', 'medium', 'full'
    default: full
  version:
    description: BookML version (if the `bookml` folder is already present, this only affects which Docker image is used)
    default: latest
  replace-bookml:
    description: Replace the `bookml` folder, if present, with the one provided by the Docker image
    default: false
  timeout-minutes:
    description: The maximum number of minutes to run BookML before cancelling the build
    default: 6

runs:
  using: composite
  steps:
    - name: Checkout the current repository
      if: inputs.checkout
      uses: actions/checkout@v4

    # GitHub does not allow dynamic inputs in 'uses', so we need to pull the Docker image by hand
    - name: Compile with BookML
      id: bookml
      shell: sh
      env:
        SCHEME: ${{ inputs.scheme }}
        VERSION: ${{ inputs.version }}
        REPLACE_BOOKML: ${{ inputs.replace-bookml }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
      run: |
        ### Compile with BookML ###
        "${{ github.action_path }}/compile.sh"

    - name: Upload outputs
      if: inputs.release
      shell: sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OUTCOME: ${{ steps.bookml.outputs.outcome }}
        TARGETS: ${{ steps.bookml.outputs.targets }}
        MESSAGE: ${{ github.event.head_commit.message }}
        REF: ${{ github.ref_name }}
        RUN: ${{ github.run_number }}
      run: |
        ### Upload outputs ###
        "${{ github.action_path }}/release.sh"
